name: skua-biocom
version: "3.8"

services:
  biocom:
    user: root
    build:
      context: .
    image: biocom-bot
    container_name: biocom-bot
    restart: unless-stopped
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    env_file:
      - .env
    volumes:
      - ./uploads/missions:/app/uploads/missions:rw
      - ./uploads/presets:/app/uploads/presets:rw
      # Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro